### ISSUE TITLE
目前的 docker 脚本不太好用

### ISSUE THREAD

**Issue by wuhunyu** [jsl1992/JiChat#2]
#### 问题说明
1. 直接跑脚本，`nacos` 容器会出错。问题原因在于找不到 `nacos` 数据库
2. `docker-compose.yml` 中设置 `mysql` 容器的 `root` 密码是 `123456`，`chat-service-app` 和 `user-service-app` 中使用的密码是 `root`
3. `docker-compose.yml` 中设置 `rabbitmq` 容器的默认用户名称是 `admin`，`chat-service-app` 和 `user-service-app` 中使用的密码是 `dream`
4. `com.ji.jichat.chat.ChatServerApplication` 主启动类 `@MapperScan` 注解扫描的类路径 `com.ji.mall.product.mapper` 不存在，不过不会影响项目启动
5. `ChatClientApplication` 启动调用登录接口，数据库并无 `jisl` 用户，期望在 `jichat_user.sql` 中加入此脚本

**Comment by wuhunyu** [comment]
关于问题1我提交了一个pr #3

**Comment by jsl1992** [comment]
1.这边也考虑过这个问题，这个是脚本适用于基础组件都没有部署。有时候，在个人环境一般都已经安装好了MySQL，Redis组件。这些组件部署，很多是已经有了。所以，没有特别指定组件和项目挂钩。
4.这个我删除下，扫描类，我统一封装在mybatis-了。
5.我这边加入

**Comment by wuhunyu** [comment]
> 1.这边也考虑过这个问题，这个是脚本适用于基础组件都没有部署。有时候，在个人环境一般都已经安装好了MySQL，Redis组件。这些组件部署，很多是已经有了。所以，没有特别指定组件和项目挂钩。 4.这个我删除下，扫描类，我统一封装在mybatis-了。 5.我这边加入

关于问题1，我一般认为一个项目所使用的组件应该是独立的。不过开发阶段倒不需要这么做，有现成的组件可以复用更节省资源
